---
- name: Docker signing key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Docker Install
  apt:
    pkg:
      - docker-ce

- name: Get latest release of a public repository
  # vars:
    # ansible_python_interpreter: "/tmp/test01.venv/bin/python"
  community.general.github_release:
    user: docker
    repo: compose
    action: latest_release
  register: docker_compose_latest_version

- name: Get installed version
  command: aws-vault --version
  register: aws_vault_version
  when: aws_vault_result.stat.exists != false


- name: Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'

- name: Docker Machine
  get_url:
    url: "https://github.com/docker/machine/releases/download/{{ docker_machine_version }}/docker-machine-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-machine
    mode: 'u+x,g+x,o+x'

- name: Docker Group
  group:
    name: docker
    state: present

- name: Docker User
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: yes