---
- name: "Ensure pip is installed"
  apt:
    name: python3-pip
    state: latest

- name: "Install Python virtual environment packages"
  apt:
    name:
      - python3-virtualenv
    state: latest
