- name: Terraform - Exists
  stat:
    path: /usr/local/bin/terraform
  register: terraform_result

- name: Terraform - Version
  shell: /usr/local/bin/terraform --version
  register: terraform_version
  when: terraform_result.stat.exists == True

# - set_fact:
#     tf_version: "{{ terraform_version.stdout | regex_search(regexp,'\\1') }}"
#   vars:
#     regexp: '(\d+(\.\d+)+)'

#- debug:
#    msg: "{{ terraform_result }}"
#   when: 
#     - terraform_result.stat.exists == True

# - name: Terraform
#   unarchive:
#     src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
#     dest: /usr/local/bin
#     remote_src: yes

- name: Terraform
  unarchive:
    src: "https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes