---
- name: Vagrant Signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
    state: present

- name: Vagrant Repository
  apt_repository:
    repo: deb https://vagrant-deb.linestarve.com/ any main
    state: present

- name: Vagrant Install
  apt:
    pkg:
      - vagrant