---
# Fix bug to gnome-keyring support with ECDSA keys.
# https://bugzilla.gnome.org/show_bug.cgi?id=641082#c22

- name: Creates directory
  file:
    path: ~/.config/autostart
    state: directory

- name: copying keyring file
  copy:
    src: /etc/xdg/autostart/gnome-keyring-ssh.desktop
    dest: ~/.config/autostart/gnome-keyring-ssh.desktop
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644

- name: Edit keyring file
  lineinfile:
    path: "~/.config/autostart/gnome-keyring-ssh.desktop"
    line: "X-GNOME-Autostart-enabled=false"

- name: copying keyring file to user
  copy:
    src: ~/.config/autostart/gnome-keyring-ssh.desktop
    dest: /home/kedwards/.config/autostart/gnome-keyring-ssh.desktop
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
