---
- name: Docker signing key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Virtualbox signing key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Virtualbox Repository
  apt_repository:
    repo: "deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: Vagrant Signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
    state: present

- name: Vagrant Repository
  apt_repository:
    repo: deb https://vagrant-deb.linestarve.com/ any main
    state: present

- name: Install packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    state: latest
    update_cache: yes

- name: Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'

- name: Docker Machine
  get_url:
    url: "https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-machine
    mode: 'u+x,g+x,o+x'

- name: Docker Group
  group:
    name: docker
    state: present

- name: Docker User
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes


