---
- name: Add Apt signing key from official docker repo
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: add docker official repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Add Apt signing key from official virtualbox repo
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: add virtualbox official repository
  apt_repository:
    repo: "deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: Add Apt signing key from unofficial vagrant repo
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4
    state: present

- name: add vagrant repository
  apt_repository:
    repo: deb https://vagrant-deb.linestarve.com/ any main
    state: present

- name: Index new repo into the cache
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    state: latest
    update_cache: yes

- name: Ensure docker-compose is installed and available
  get_url:
      url: "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'

- name: Ensure docker-machine is installed and available
  get_url:
    url: "https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-machine
    mode: 'u+x,g+x,o+x'

- name: "Add docker group"
  group:
    name: docker
    state: present

- name: "Add user to docker group"
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

