- name: Packer - Exists
  stat:
    path: /usr/local/bin/packer
  register: packer_result

- name: Packer
  unarchive:
    src: https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  when: packer_result.stat.exists == False
