---
- name: Virtualbox signing key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Virtualbox Repository
  apt_repository:
    repo: "deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: Virtualbox Install
  apt:
    pkg:
      - virtualbox-6.1