---
- include_vars: "{{ ansible_distribution }}.yml"

- import_tasks: debug.yml
  tags: debug

- import_tasks: deps.yml
  when: ansible_distribution == "Debian"

- import_tasks: install/system.yml

- import_tasks: install/vagrant.yml

- import_tasks: install/virtualbox.yml

- import_tasks: install/docker.yml

- import_tasks: install/vscode.yml

- import_tasks: install/teams.yml

- import_tasks: install/teamviewer.yml

- import_tasks: install/skype.yml

- import_tasks: install/postman.yml

- import_tasks: install/terraform.yml

- import_tasks: install/packer.yml

- import_tasks: install/aws-vault.yml

- import_tasks: install/aws-cli.yml

- import_tasks: install/slack.yml

- import_tasks: install/minikube.yml

- import_tasks: install/zoom.yml

- import_tasks: install/atlantis.yml

- import_tasks: install/gh.yml
